### ISSUE TITLE
code 400, message Bad request syntax

### ISSUE THREAD

**Issue by KelSolaar** [shotgunsoftware/sg-jira-bridge#28]
Hi,

This relates to our testing in #26. I noticed those exceptions being raised, although they do not seem to affect the web app so far:

```
2019-09-17 08:33:27,712 INFO [bridge] Successfully read settings from ***/sg-jira-bridge/settings.py
2019-09-17 08:33:28,038 INFO [shotgun_session] Connected to https://***.shotgunstudio.com.
2019-09-17 08:33:28,713 INFO [jira_session] Connected to https://***.atlassian.net.
2019-09-17 08:35:38,089 INFO [note_comment_handler] Jira issue ***-28 Comment 11918 updated. Syncing to Shotgun Note (7321)
2019-09-17 08:35:46,549 INFO [note_comment_handler] Shotgun Note (7322) added. Adding as a comment on Jira Issue ***-28
2019-09-17 08:35:47,011 INFO [note_comment_handler] Updating Shotgun Note (7322) with Jira comment key ***-28/11920
2019-09-17 08:35:47,660 INFO [note_comment_handler] Shotgun Note (7322) updated. Syncing to Jira Issue ***-28 Comment 11920
2019-09-17 08:35:52,302 ERROR [webapp] 13.237.238.24 - code 400, message Bad request syntax ('\x16\x03\x03\x01')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/local/lib/python2.7/ssl.py", line 745, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
2019-09-17 08:35:52,814 INFO [note_comment_handler] Shotgun Note (7322) updated. Syncing to Jira Issue ***-28 Comment 11920
2019-09-17 08:35:57,600 ERROR [webapp] 13.237.238.24 - code 400, message Bad request syntax ('\x16\x03\x03\x01')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/SocketServer.py", line 293, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/local/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/local/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/local/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  File "/usr/local/lib/python2.7/ssl.py", line 745, in sendall
    return socket.sendall(self, data, flags)
  File "/usr/local/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 32] Broken pipe
```

**Comment by unquietwiki** [comment]
@KelSolaar I opened #31 yesterday: it might help figure this out.
